baseURL = "https://blog.serafi.dev/"
languageCode = "en-us"
title = "serafí's blog"
theme = "archie"

copyright = "© Serafí Nebot"
[params]
    mode = "toggle"
    katex = true
    chromaLight = "github"
    chromaDark  = "dracula"

[params.author]
    email = "hexdhog@proton.me"
    name = "Serafí Nebot"

[markup]
    [markup.highlight]
        codeFences = true
        guessSyntax = true
        lineNos = false  # Optional: Set to true if you want line numbers
        noClasses = false  # Crucial: Enables classes for CSS styling
        style = "github"  # Default fallback; will be overridden by our custom CSS
        tabWidth = 4
        # style = "base16-snazzy"
        # style = "gruvbox"
        # style = "monokai"
        # style = "onedark"
        # style = "paraiso-dark"

[[params.social]]
    name = "GitHub"
    icon = "github"
    url = "https://github.com/hexdhog/"

[[params.social]]
    name = "X"
    icon = "twitter"
    url = "https://x.com/serafinebot/"

[services]
    [services.rss]
        limit = -1

[outputs]
    home = ["html", "rss"]
