baseURL = "https://hexdhog.com/"
languageCode = "en-us"
title = "hexdhog"
theme = "archie"

copyright = "Â© hexdhog"
[params]
mode = "dark"
katex = true
[params.author]
email = "hexdhog@pm.me"
name = "hexdhog"

[markup]
[markup.highlight]
codeFences = true
style = "base16-snazzy"
# style = "gruvbox"
# style = "monokai"
# style = "onedark"
# style = "paraiso-dark"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/hexdhog/"

[[params.social]]
name = "X"
icon = "twitter"
url = "https://twitter.com/hexdhog/"

[services]
[services.rss]
limit = -1

[outputs]
home = ["html", "rss"]
