baseURL = "https://blog.serafi.dev/"
languageCode = "en-us"
title = "serafí's blog"
theme = "archie"

copyright = "© Serafí Nebot"
[params]
    mode = "toggle"
    katex = true
    chromaLight = "github"
    chromaDark  = "github-dark"

[params.author]
    email = "hexdhog@proton.me"
    name = "Serafí Nebot"

[markup]
    [markup.highlight]
        codeFences = true
        guessSyntax = true
        lineNos = false
        tabWidth = 4

        # TODO: fix highlight colorscheme change on theme toggle
        # noClasses = false
        style = "github-dark"
        # style = "github"

        # style = "dracula"
        # style = "doom-one2"
        # style = "doom-one"
        # style = "base16-snazzy"
        # style = "gruvbox"
        # style = "monokai"
        # style = "onedark"
        # style = "paraiso-dark"

[[params.social]]
    name = "GitHub"
    icon = "github"
    url = "https://github.com/hexdhog/"

[[params.social]]
    name = "X"
    icon = "twitter"
    url = "https://x.com/serafinebot/"

[services]
    [services.rss]
        limit = -1

[outputs]
    home = ["html", "rss"]
